### ISSUE TITLE
请教一下，我和你同型号华硕，interWIFI驱动不了

### ISSUE THREAD

**Issue by Weiming-Li** [deanls1/asus-n551jw4200hackintosh10.15#2]
能说下你具体装Macos catalina10.15那个版本，我目前装是的Macos catalina10.15.5，导入你efi，WIFI驱动不了，提示正在搜索网络，谢谢

**Comment by deanls1** [comment]
应该是10.15.4以前的，你可以试一下

**Comment by Weiming-Li** [comment]
> 应该是10.15.4以前的，你可以试一下

你电脑在身边的话，有时间可以看一下具体版本么，现在百度网盘限速太厉害了

**Comment by deanls1** [comment]
我已经换电脑了，你可以去黑果小兵那下载，有个比特彗星的软件，可以多线程下载

**Comment by Weiming-Li** [comment]
> 我已经换电脑了，你可以去黑果小兵那下载，有个比特彗星的软件，可以多线程下载
> 

谢谢，我找了新的无线驱动可以了
